### Project 0

In [64]:
import numpy as np
import matplotlib as plt
import scipy.linalg

In [67]:
def eulerstep(A, uold, h):
    y_prim = A@uold
    unew = uold + y_prim*h
    return unew

def eulerint(A, y0, t0, tf, N):
    y_new =  eulerstep(A, y0, (tf-t0)/N) #first step
    for i in range(N-1):
        y_new = eulerstep(A, y_new, (tf-t0)/N)
    
    exact_value = scipy.linalg.expm(tf*A)
    print(exact_value)
    tgrid = 0
    approx = y_new
    err = exact_value-approx
    return tgrid, approx, err

In [60]:
A = np.array([[1,2],[3,4]])
uold = np.array([1,2])
h = 0.1
eulerstep(A, uold, h)
#eulerstep 

array([1.5, 3.1])

In [68]:
y0 =np.array([1,2])
t0 = 0
tf = 2
N = 10
eulerint(A, y0, t0, tf, N)

[[11079.1035333  16146.29362577]
 [24219.44043865 35298.54397195]]


(0,
 array([1380.23810888, 3017.30878863]),
 array([[ 9698.86542442, 13128.98483713],
        [22839.20232977, 32281.23518331]]))